### ISSUE TITLE
LiPROD 1.0.0-alpha | Traceback_error

### ISSUE THREAD

**Issue by jkspring** [noaa-rsd/LiProd#5]
I get the following error when running on following project:
**FL1613_BLK02**

**Project_Directory:**
\\ngs-s-rsd\Lidar_Proc01\2016\FL1613-TB-N-880_KeysOuterReef_02_p
**las_tpu_directory:**
//ngs-s-rsd/Geocue01/iocm_deliverables/lidar/FL1613-TB-N/02/las_tpu_v2.1.1_no_mcu

_C:\LiProd-1.0.0-alpha>ECHO off
"starting lidog..."
100%|#############################################################################| 1229/1229 [00:03<00:00, 344.16it/s]
Traceback (most recent call last):
  File "C:\LiProd-1.0.0-alpha\LiPROD.py", line 398, in <module>
    for i, cell in liprod.cells_gdf.iterrows():
  File "C:\LiProd-1.0.0-alpha\LiPROD.py", line 273, in cells_gdf
    return self.get_intersecting_cells(self.las_gdf,
  File "C:\LiProd-1.0.0-alpha\LiPROD.py", line 344, in las_gdf
    return self.get_tiles()
  File "C:\LiProd-1.0.0-alpha\LiPROD.py", line 335, in get_tiles
    crs_init = self.get_las_crs_init()
  File "C:\LiProd-1.0.0-alpha\LiPROD.py", line 320, in get_las_crs_init
    crs = CRS.from_string(hor_wkt)
  File "C:\Users\Jamie.Kum\.conda\envs\liprod\lib\site-packages\rasterio\crs.py", line 342, in from_string
    raise CRSError("CRS is empty or invalid: {!r}".format(string))
rasterio.errors.CRSError: CRS is empty or invalid: ''
(liprod) C:\LiProd-1.0.0-alpha>_

**Comment by forkozi** [comment]
due to an anomalous las file;  will add try/except to check for this case
